### ISSUE TITLE
RecyclerView用不了

### ISSUE THREAD

**Issue by super-hu** [bboyfeiyu/Chris-Android-PullToRefresh#1]
跑着就崩溃了
 java.lang.NullPointerException
                                                                                        at com.handmark.pulltorefresh.library.PullToRefreshRecyclerView.isReadyForPullEnd(PullToRefreshRecyclerView.java:121)
                                                                                        at com.handmark.pulltorefresh.library.PullToRefreshBase.isReadyForPull(PullToRefreshBase.java:1152)
                                                                                        at com.handmark.pulltorefresh.library.PullToRefreshBase.onInterceptTouchEvent(PullToRefreshBase.java:290)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1886)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1944)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1944)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1944)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2243)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1944)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2243)
                                                                                        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1548)
                                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2509)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2069)
                                                                                        at android.view.View.dispatchPointerEvent(View.java:7901)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4295)
                                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4174)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3783)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3859)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
                                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3916)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
                                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3783)
                                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
                                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
                                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
                                                                                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5899)
                                                                                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5863)
                                                                                        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5834)
                                                                                        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5979)
                                                                                        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                        at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                                        at android.os.Looper.loop(Looper.java:123)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5032)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by super-hu** [comment]
在第一次没有数据的情况下会出错，有什么解决方法？

**Comment by hehonghui** [comment]
@hcadoid 这是 Chris 的库里面出了问题，里面有源码，你可以从源码修改一下
